### ISSUE TITLE
Unknown camera ID after upgrade to LineageOS 17.1/Android 10

### ISSUE THREAD

**Issue by 0x4c47** [jlvcm/Simple-Camera#2]
First of all, great work. I love the idea of this app.

After I recently upgraded to LineageOS 17.1 and with that to Android 10, the app stopped working.

Upon opening an error message is shown:
"An error occurred: Get camera characteristics java.lang.IllegalArgumentException:
supportsCameraApi:1980: Unknown camera ID 5"

I saw that one of the last commits actually was about hard-coding the camera ID. So maybe it's related to that?

Phone: Pocophone F1 Global Version
It all worked under LineageOS 16/Android 9.
It now doesn't work under LineageOS 17.1/Android 10.
With the update I also needed to update the Xiaomi firmware. Current firmware is V11.0.6.0.QEJMIXM from https://xiaomifirmwareupdater.com/firmware/beryllium/
I'm not sure on what exact version I was before but it definitely was one of the Android 9 ones.

**Comment by jlvcm** [comment]
I believe some lineage Android 10 does not have the infrared camera working
as they don't use it for face unlock, you may ask the rom creator thought.

I try to test it on some random roms from time to time, if there is some
fix I'll let you know

**Comment by 0x4c47** [comment]
For some reason it started working again with one of the recent OTA LineageOS updates. I just randomly installed it again today to try it and it just worked. Seems like this was an issue of LineageOS.
